JTT.WebApplication/Controllers/DeckController.cs
using JTT.Domain.DTO;
using JTT.Interfaces;
using JTT.WebApplication.Filters;
using JTT.WebApplication.Models;
using JTT.WebApplication.Models.Game;
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JTT.WebApplication.Utilities;

using JTT.SharedComponents;

namespace JTT.WebApplication.Controllers
{
    public class DeckController : Controller
    {
        private readonly IDeckBusinessLogic _deckBusinessLogic;
        private readonly IDeckCategoryBusinessLogic _deckCategoryBusinessLogic;
        private readonly ICardBusinessLogic _cardBusinessLogic;
        private readonly ICardCategoryBusinessLogic _cardCategoryBusinessLogic;

        CloudStorageAccount storageAccount;
        CloudBlobClient blobClient;
        CloudBlobContainer container;

        public DeckController(IDeckBusinessLogic deckBusinessLogic, IDeckCategoryBusinessLogic deckCategoryBusinessLogic, ICardBusinessLogic cardBusinessLogic, ICardCategoryBusinessLogic cardCategoryBusinessLogic)
        {
            _deckBusinessLogic = deckBusinessLogic;
            _deckCategoryBusinessLogic = deckCategoryBusinessLogic;
            _cardBusinessLogic = cardBusinessLogic;
            _cardCategoryBusinessLogic = cardCategoryBusinessLogic;
        }

        [TopTrumpsAuthorise]
        public ActionResult Index()
        {
            var decks = _deckBusinessLogic.GetAllDecks();
            return View(decks);
        }

        public new ActionResult View(string id)
        {
            Guid deckId = Guid.Parse(id);

            Deck deck = _deckBusinessLogic.GetById(deckId);
            List<DeckCategory> deckCategories = _deckCategoryBusinessLogic.GetDeckCategoriesForDeck(deckId);
            List<Card> cards = _cardBusinessLogic.GetCardsForDeck(deck.Id);

            TopTrumpsDeck ttDeck = new TopTrumpsDeck(deck.Id, deck.Name, new List<TopTrumpsCard>());

            foreach (Card card in cards)
            {
                TopTrumpsCard ttCard = new TopTrumpsCard(card.Id, card.Name, new List<TopTrumpsCategory>(), BlobUtilities.GetBlobAddress(deck.Name, card.Id));

                foreach (CardCategory category in card.CardCategories)
                {
                    TopTrumpsCategory ttCategory = new TopTrumpsCategory()
                    {
                        CategoryId = category.Id,
                        Name = deckCategories.Find(c => c.Id == category.DeckCategoryId).Name,
                        Value = category.Score
                    };

                    ttCard.TopTrumpsCategories.Add(ttCategory);
                }

                ttDeck.TopTrumpsCards.Add(ttCard);
            }

            return View(ttDeck);
        }

        public ActionResult All()
        {
            List<Deck> decks = _deckBusinessLogic.GetAllDecks();
            List<TopTrumpsDeck> ttdecks = new List<TopTrumpsDeck>();

            foreach(Deck deck in decks)
            {
                Card card = _cardBusinessLogic.GetFirstCardForDeck(deck.Id);
                
                List<TopTrumpsCard> cards = new List<TopTrumpsCard>{ 
                    new TopTrumpsCard(card.Id, card.Name, null, BlobUtilities.GetBlobAddress(deck.Name, card.Id) ) 
                };

                ttdecks.Add(
                    new TopTrumpsDeck(
                        deck.Id, 
                        deck.Name,
                        cards
                        )
                );
            }

            return View(ttdecks);
        }

        public ActionResult Create()
        {
            DeckModel model = new DeckModel
            {
                DeckName = "Joel Deck",
                DeckCategories = new List<DeckCategoryModel>() 
                {  
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=0 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=1 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=2 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=3 }

                    //Default categories for testing purposes
                    //new DeckCategoryModel(){ CategoryName = "Intelligence", Index=0 },
                    //new DeckCategoryModel(){ CategoryName = "Cuteness", Index=1 },
                    //new DeckCategoryModel(){ CategoryName = "Emotional", Index=2 },
                    //new DeckCategoryModel(){ CategoryName = "Boyfriend Material", Index=3 },
                    //new DeckCategoryModel(){ CategoryName = "Dress Sense", Index=4 }
                }
            };
            return View(model);
        }

        public ActionResult CreateDeck(string deckName, ICollection<DeckCategoryModel> deckCategories)
        {
            DeckModel model = new DeckModel
            {
                DeckName = deckName,
                DeckCategories = deckCategories
            };

            return View(model);
        }

        public PartialViewResult AddDeckCategory(int index)
        {
            return PartialView("PartialViews/_DeckCategoryPartial", new DeckCategoryModel() { CategoryName = string.Empty, Index = index });
        }

        public ActionResult SaveDeck(string deckName, ICollection<DeckCategoryModel> deckCategories, ICollection<CardModel> cards, IEnumerable<HttpPostedFileBase> cardImages)
        {
            SetupStorageContainer(deckName);

            //Save the Deck
            Guid deckId = _deckBusinessLogic.CreateDeck(new Deck() { Name = deckName });

            ////Save the Deck Categories
            foreach (DeckCategoryModel deckCategory in deckCategories)
            {
                Guid dcId = _deckCategoryBusinessLogic.CreateDeckCategory(new DeckCategory() { Id = Guid.NewGuid(), DeckId = deckId, Name = deckCategory.CategoryName });

                //Keep track of the deck Category GUIDs so that Card Categories can be linked up
                foreach (CardModel card in cards)
                {
                    foreach (CardCategoryModel cardCategory in card.CardCategories)
                    {
                        if (cardCategory.Index == deckCategory.Index)
                        {
                            cardCategory.DeckCategoryId = dcId;
                        }
                    }
                }
            }


            //Save the Cards
            int imageInc = 0;
            foreach (CardModel card in cards)
            {
                //Get the card image from the list of files
                HttpPostedFileBase image = cardImages.ElementAt(imageInc);
                imageInc++;

                //Create a guid for the card
                Guid cardGuid = Guid.NewGuid();

                // Retrieve reference to a blob named with this guid
                CloudBlockBlob blockBlob = container.GetBlockBlobReference( cardGuid.ToString() );

                //Upload the blob
                blockBlob.UploadFromStream(image.InputStream);

                //Create Card to Save
                Card newCard = new Card
                {
                    Id = cardGuid,
                    Name = card.CardName,
                    DeckId = deckId
                };

                //Save the card object
                _cardBusinessLogic.CreateCard(newCard);

                List<CardCategory> cardCategories = new List<CardCategory>();

                //Save the Card Category Values
                foreach (CardCategoryModel cardCategory in card.CardCategories)
                {
                    cardCategories.Add(new CardCategory
                    { 
                        Id = Guid.NewGuid(), 
                        DeckCategoryId = cardCategory.DeckCategoryId, 
                        Score = cardCategory.Value, 
                        CardId = newCard.Id 
                    });
                }

                //Save the Card Category objects
                _cardCategoryBusinessLogic.CreateCardCategory(cardCategories);
            }

            return RedirectToAction("View", new { id = deckId.ToString() });
        }

        public void SetupStorageContainer(string deckname)
        {
            //Retrieve the connection string
            string connStr = ConfigurationUtilities.GetConfigurationSetting("AzureConnectionString");

            //Retrieve storage account from connection string.
            storageAccount = CloudStorageAccount.Parse(connStr);

            //Create the blob client.
            blobClient = storageAccount.CreateCloudBlobClient();

            //Retrieve a reference to a container. 
            container = blobClient.GetContainerReference(deckname.ToLower().Replace(" ", string.Empty));

            //Create the container if it doesn't already exist.
            container.CreateIfNotExists();

            //Make the card images publicly accessible
            container.SetPermissions(
            new BlobContainerPermissions
            {
                PublicAccess = BlobContainerPublicAccessType.Blob
            });
        }
    }
}

JTT.WebApplication/Controllers/MatchmakingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JTT.WebApplication.Models.Matchmaking;

namespace JTT.WebApplication.Controllers
{
    public class MatchmakingController : AuthorisedController
    {
        [HttpGet]
        public ActionResult SeekMatch(Guid? id = null)
        {
            return View(new SeekMatchModel
            {
                DeckId = id
            });
        }
    }
}

JTT.WebApplication/Views/Deck/All.cshtml
@model List<JTT.WebApplication.Models.Game.TopTrumpsDeck>

@{
    ViewBag.Title = "View Decks";
}

<div class="deckDisplay">
    <div class="deckHeader">
        <h1>Decks</h1>
        @Html.ActionLink("Create New Deck", "Create", "Deck", null, new { @class = "deckHeaderLink" })
    </div>

    @foreach (JTT.WebApplication.Models.Game.TopTrumpsDeck deck in Model)
    {
        <div class="card deckThumb">
            <a href="@Url.Action("View", "Deck", new { id = @deck.Id })">
                <header>

                    <img src="@deck.TopTrumpsCards.First().ImageAddress" width="320" height="320" />

                    <div class="titleContainer">
                        <span class="deckName">@deck.Name</span>
                    </div>
                </header>
            </a>
        </div>
    }
</div>

JTT.WebApplication/Views/Deck/Create.cshtml
@model JTT.WebApplication.Models.DeckModel
@{
    ViewBag.Title = "Create a Deck";
}

<script>
    $(document).ready(function () {
        $("#AddDeckCategory").click(function () {
            $.ajax({
                url: this.href,
                data: { index: deckCategoryIndex() },
                cache: false,
                success: function (partialViewHtml) {
                    $("#deckCategories").append(partialViewHtml);
                    incrementDeckCategoryIndex();
                },
                error: function () {
                    alert("Oh god.\n\nIts happened again.");
                }
            });

            return false;
        });
        function deckCategoryIndex()
        {
            return parseInt($('#hdnDeckCategoryIndex').val());
        }
        function incrementDeckCategoryIndex()
        {
            $('#hdnDeckCategoryIndex').val(deckCategoryIndex() + 1);
        }
        function decrementDeckCategoryIndex() {
            $('#hdnDeckCategoryIndex').val(deckCategoryIndex() - 1);
        }

        $('#pg1-next').click(function () {
            $('#pg1').fadeOut(200, function () {
                $('#pg2').fadeIn(200);
                $('.form-progress-line.step1-line').addClass('complete');
                $('.form-progress-step.step2').addClass('complete');
            });
            return false;
        });

        $('#pg2-back').click(function () {
            $('#pg2').fadeOut(200, function () {
                $('#pg1').fadeIn(200);
                $('.form-progress-line.step1-line').removeClass('complete');
                $('.form-progress-step.step2').removeClass('complete');
            });
            return false;
        });

        $('.step1').click(function () {
            $('#pg2').fadeOut(200, function () {
                $('#pg1').fadeIn(200);
                $('.form-progress-line.step1-line').removeClass('complete');
                $('.form-progress-step.step2').removeClass('complete');
            });
            return false;
        });

        $('.step2').click(function () {
            $('#pg1').fadeOut(200, function () {
                $('#pg2').fadeIn(200);
                $('.form-progress-line.step1-line').addClass('complete');
                $('.form-progress-step.step2').addClass('complete');
            });
            return false;
        });



        $(document).on('click', '.removeDeckCategory', function () {
            var indexToDelete = $(this).closest('.category').attr('data-catindex');

            var tempCatName = '';
            var temptempCatName = '';
            var firstRun = true;

            $($('.category').get().reverse()).each(function () {

                if ($(this).attr('data-catindex') >= indexToDelete) {

                    var input = $(this).find('.category-input');

                    if (firstRun) {
                        tempCatName = input.val();
                        $(this).remove();
                        firstRun = false;
                    } else {
                        temptempCatName = tempCatName;
                        tempCatName = input.val();
                        input.val(temptempCatName);
                    }

                }

            });

            decrementDeckCategoryIndex();
        });
    });
</script>


<style>
    body {
        background: #354458;
        background-color: #354458;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 14px;
        line-height: 1.428;
        color: #2b2828;
    }

    .container {
        width: 90%;
        max-width: 640px;
        margin: 0 auto 60px auto;
    }

    .main {
        background-color: rgba(240, 240, 240, 1);
        -webkit-border-radius: 3x;
        border-radius: 3px;
        -webkit-box-shadow: 0 0 5px 5px rgba(0,0,0,0.1);
        box-shadow: 0 0 5px 5px rgba(0,0,0,0.1);
        padding: 5%;
    }

    h1 {
        text-align: center;
        color: white;
        margin: 40px 0 20px 0;
        width: 100%;
        font-size: 36px;
        font-weight: bold;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    }

    h2 {
        margin: 0 0 25px 0;
        width: 100%;
        font-size: 28px;
        font-weight: bold;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        color: #2b2828;
    }

    p {
        color: #2b2828;
        font-size: 1em;
        margin-bottom: 0.5em;
    }

    .form-row {
        margin-bottom: 15px;
    }

    .form-input {
        display: block;
        width: 100%;
        max-width: 400px;
        margin: auto;
        padding: 5px 12px;
        font-size: 1.1em;
        font-size: 1em;
        box-sizing: border-box;
    }

    .form-button {
        border: 0 none;
        -webkit-border-radius: 2x;
        border-radius: 2px 2px 2px 2px;
        cursor: pointer;
        line-height: 20px;
        padding: 8px 12px;
        text-transform: none;
        transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -webkit-transition: all 0.3s ease 0s;
        text-align: center;
    }

    .form-button-main {
        background-color: #3a9ad9;
        color: white;
    }

        .form-button-main:hover {
            background-color: #188fdd;
        }

    .form-button-highlight {
        background-color: #edc740;
        color: white;
    }

        .form-button-highlight:hover {
            background-color: orange;
            color: white;
            text-decoration: none;
        }

        .form-button-highlight:active {
            background-color: #188fdd;
            color: white;
            text-decoration: none;
        }


    .form-button > .fa-right {
        display: inline-block;
        margin: 1px 0 0 3px;
    }

    .form-button > .fa-left {
        display: inline-block;
        margin: 1px 3px 0 0;
    }

    #deckCategories {
        margin: 5% 0 0 0px;
        box-sizing: border-box;
    }

        #deckCategories > .category {
            width: 100%;
            margin: 2% 0px;
            box-sizing: border-box;
        }

            #deckCategories > .category > .category-name {
                width: 68%;
                display: inline-block;
            }

            #deckCategories > .category > .category-checkbox {
                width: 30%;
                display: inline-block;
                text-align: center;
            }

    #AddDeckCategory {
        display: block;
        box-sizing: border-box;
        width: 64.6%;
        max-width: 400px;
        padding: 8px 12px;
        font-size: 1.1em;
        font-size: 1em;
        border: 0 none;
        -webkit-border-radius: 2x;
        border-radius: 2px 2px 2px 2px;
        cursor: pointer;
        line-height: 20px;
        text-transform: none;
        transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -webkit-transition: all 0.3s ease 0s;
        text-align: center;
        background-color: #edc740;
        color: white;
        margin-bottom: 10%;
    }

        #AddDeckCategory:hover {
            background-color: orange;
            text-decoration: none;
        }

    .backPreviousButtons {
        margin: auto;
        text-align: center;
        box-sizing: border-box;
    }

    #pg2-back {
        width: 49%;
        display: inline-block;
        box-sizing: border-box;
        margin: 0 2% 0 0;
    }

    #pg2-next {
        width: 49%;
        display: inline-block;
        box-sizing: border-box;
        margin: 0px;
    }

    #pg2 {
        display: none;
    }

    #fileSelect {
        margin-top: 25px;
    }

    #fileList {
        display: none;
        margin-top: 25px;
    }

    #SaveCards {
        display: none;
        margin-top: 40px;
    }

        #SaveCards > button {
            padding: 20px;
            font-size: 1.5em;
        }

    .form-progress {
        text-align: center;
        margin-bottom: 40px;
    }

    .form-progress-step {
        display: inline-block;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        color: #000000;
        background-color: #f5f5f5;
        padding: 5px 0;
        width: 30px;
        text-align: center;
    }

    .form-progress-line {
        display: inline-block;
        background-color: #f5f5f5;
        width: 10%;
        height: 5px;
        margin: 0px -5px 0px -5px;
    }

    .form-progress-step.complete {
        color: #ffffff;
        background-color: #edc740;
    }

    .form-progress-line.complete {
        background-color: #edc740;
    }

    .cursorHand {
        cursor: pointer;
    }

    .clearFloats {
        clear: both;
    }

    .card {
        float: left;
        width: 28%;
        min-width: 200px;
        height: auto;
        margin: 2%;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
    }

        .card img {
            width: 100%;
        }

    .cardinfo {
        background-color: #edc740;
        width: 100%;
        padding: 3%;
        margin: 0px;
        box-sizing: border-box;
    }

    .cardName {
        width: 97%;
        display: block;
        font-size: 0.7em;
        color: #2b2828;
        font-weight: bold;
    }

    .cardinfo > input {
        width: 97%;
        margin: 3px 0 7px 0;
        padding: 3px 5px;
        box-sizing: border-box;
        text-align: center;
    }

    .category {
        width: 100%;
    }

    .categoryName {
        width: 97%;
        display: block;
        font-size: 0.7em;
        color: #2b2828;
        font-weight: bold;
        margin-top: 3px;
    }

    .categoryValue {
        width: 97%;
        padding: 3px 5px;
        box-sizing: border-box;
        text-align: center;
    }


    .category-input{
        width:95%;
        display:inline-block;
        padding:5px 30px 5px 12px;
    }
    .removeDeckCategory{
        color:red;
        display:inline-block;
        cursor:pointer;
    }
</style>


<div class="container">

    <h1>Create a Deck</h1>

    <div class="form-progress">
        <div class="form-progress-step step1 complete cursorHand">1</div>
        <div class="form-progress-line step1-line"></div>
        <div class="form-progress-step step2 cursorHand">2</div>
        <div class="form-progress-line step2-line"></div>
        <div class="form-progress-step step3">3</div>
        <div class="clearFloats"></div>
    </div>


    <main role="main" class="main">
        @using (Html.BeginForm("CreateDeck", "Deck", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div id="pg1">
                <h2>Step 1: Name Your Deck</h2>
                <div class="pg1_main">
                    <div class="form-row">
                        <input type="text" class="form-input" name="deckName" id="deckName" placeholder="Deck Name" />
                    </div>
                    <div class="form-row">
                        <button id="pg1-next" class="form-input form-button form-button-main">
                            Next <i class="fa fa-arrow-right fa-right"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div id="pg2">
                <h2>Step 2: Category Setup</h2>
                <p>Each deck must have at least four categories in order to play. For example, a car-themed deck might have a categories for engine size, top speed, acceleration and price.</p>
                <p>You will also need to select whether a higher number or a lower number is considered to be better for each category. For example if the category was a car's 0-60mph acceleration time, then lower numbers will beat higher numbers.</p>
                <div id="deckCategories">
                    <input id="hdnDeckCategoryIndex" type="hidden" value="@Model.DeckCategories.Count()" />
                    @foreach (var category in Model.DeckCategories)
                    {
                        Html.RenderPartial("PartialViews/_DeckCategoryPartial", category);
                    }
                </div>

                <a id="AddDeckCategory" href="@Url.Action("AddDeckCategory")">
                    Add Another Category <i class="fa fa-plus fa-right"></i>
                </a>

                <div class="form-row backPreviousButtons">
                    <button id="pg2-back" class="form-input form-button form-button-main">
                        <i class="fa fa-arrow-left fa-left"></i> Back
                    </button><button id="pg2-next" type="submit" class="form-input form-button form-button-main">
                        Next <i class="fa fa-arrow-right fa-right"></i>
                    </button>
                </div>
            </div>
        }

    </main>

</div>

JTT.WebApplication/Views/Deck/Index.cshtml
@model List<JTT.Domain.DTO.Deck>

@{
    ViewBag.Title = "Deck Select";
}

<div class="center-container">
    <h1>Choose your Deck...</h1>

    @Html.DropDownList("Deck", new List<SelectListItem>(@Model.Select(d => new SelectListItem
        { Text = d.Name, Value = d.Id.ToString() })), new { @id = "Decks", @class = "dropdown" })

    <a class="deck-select matchmake">
        Matchmake Me
    </a>
    <a class="deck-select private">
        Start Private Match
    </a>
</div>

<script type="text/javascript">
    var seekMatchUrl = '@Url.Action("SeekMatch", "Matchmaking")';
    var privateMatchUrl = '@Url.Action("PrivateGame", "Game")';

    $(function () {
        $(".deck-select").click(function () {
            var selectedItem = $("#Decks option:selected");

            window.location = seekMatchUrl + "/" + selectedItem.val();
        });

        $(".private").click(function () {
            var selectedItem = $("#Decks option:selected");

            window.location = privateMatchUrl + "?deckId=" + selectedItem.val();
        });
    });
</script>

JTT.WebApplication/Views/Deck/View.cshtml
@model JTT.WebApplication.Models.Game.TopTrumpsDeck

@{
    ViewBag.Title = "Create Cards";
}

<div class="deckDisplay">
    <div class="deckHeader">
        <h1>@Model.Name</h1>
        @Html.ActionLink("< Back to All Decks", "All", "Deck", null, new { @class = "deckHeaderLink" })
    </div>

    <div class="deckCards">
        @foreach (JTT.WebApplication.Models.Game.TopTrumpsCard card in Model.TopTrumpsCards)
        {
            <div class="card face">

                <header>

                    <img src="@card.ImageAddress" width="320" height="320" />

                    <div class="titleContainer">
                        <span class="title">@card.Name</span>
                    </div>
                    <div class="slantedBlock"></div>

                </header>

                <div class="categories">

                    <table class="selectable">

                        <tbody>
                            @foreach (JTT.WebApplication.Models.Game.TopTrumpsCategory category in @card.TopTrumpsCategories)
                            {
                                <tr class="card-category">
                                    <th>@category.Name</th>
                                    <th>@category.Value</th>
                                </tr>
                            }
                        </tbody>

                    </table>

                </div>

                <footer>
                    &copy; Joel Top Trumps - @DateTime.Now.Year
                </footer>

            </div>

        }
    </div>

</div>