JTT.WebApplication/Controllers/DeckController.cs
using JTT.Domain.DTO;
using JTT.Interfaces;
using JTT.WebApplication.Filters;
using JTT.WebApplication.Models;
using JTT.WebApplication.Models.Game;
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JTT.WebApplication.Utilities;

using JTT.SharedComponents;

namespace JTT.WebApplication.Controllers
{
    public class DeckController : Controller
    {
        private readonly IDeckBusinessLogic _deckBusinessLogic;
        private readonly IDeckCategoryBusinessLogic _deckCategoryBusinessLogic;
        private readonly ICardBusinessLogic _cardBusinessLogic;
        private readonly ICardCategoryBusinessLogic _cardCategoryBusinessLogic;

        CloudStorageAccount storageAccount;
        CloudBlobClient blobClient;
        CloudBlobContainer container;

        public DeckController(IDeckBusinessLogic deckBusinessLogic, IDeckCategoryBusinessLogic deckCategoryBusinessLogic, ICardBusinessLogic cardBusinessLogic, ICardCategoryBusinessLogic cardCategoryBusinessLogic)
        {
            _deckBusinessLogic = deckBusinessLogic;
            _deckCategoryBusinessLogic = deckCategoryBusinessLogic;
            _cardBusinessLogic = cardBusinessLogic;
            _cardCategoryBusinessLogic = cardCategoryBusinessLogic;
        }

        [TopTrumpsAuthorise]
        public ActionResult Index()
        {
            var decks = _deckBusinessLogic.GetAllDecks();
            return View(decks);
        }

        public new ActionResult View(string id)
        {
            Guid deckId = Guid.Parse(id);

            Deck deck = _deckBusinessLogic.GetById(deckId);
            List<DeckCategory> deckCategories = _deckCategoryBusinessLogic.GetDeckCategoriesForDeck(deckId);
            List<Card> cards = _cardBusinessLogic.GetCardsForDeck(deck.Id);

            TopTrumpsDeck ttDeck = new TopTrumpsDeck(deck.Id, deck.Name, new List<TopTrumpsCard>());

            foreach (Card card in cards)
            {
                TopTrumpsCard ttCard = new TopTrumpsCard(card.Id, card.Name, new List<TopTrumpsCategory>(), BlobUtilities.GetBlobAddress(deck.Name, card.Id));

                foreach (CardCategory category in card.CardCategories)
                {
                    TopTrumpsCategory ttCategory = new TopTrumpsCategory()
                    {
                        CategoryId = category.Id,
                        Name = deckCategories.Find(c => c.Id == category.DeckCategoryId).Name,
                        Value = category.Score
                    };

                    ttCard.TopTrumpsCategories.Add(ttCategory);
                }

                ttDeck.TopTrumpsCards.Add(ttCard);
            }

            return View(ttDeck);
        }

        public ActionResult All()
        {
            List<Deck> decks = _deckBusinessLogic.GetAllDecks();
            List<TopTrumpsDeck> ttdecks = new List<TopTrumpsDeck>();

            foreach(Deck deck in decks)
            {
                Card card = _cardBusinessLogic.GetFirstCardForDeck(deck.Id);
                
                List<TopTrumpsCard> cards = new List<TopTrumpsCard>{ 
                    new TopTrumpsCard(card.Id, card.Name, null, BlobUtilities.GetBlobAddress(deck.Name, card.Id) ) 
                };

                ttdecks.Add(
                    new TopTrumpsDeck(
                        deck.Id, 
                        deck.Name,
                        cards
                        )
                );
            }

            return View(ttdecks);
        }

        public ActionResult Create()
        {
            DeckModel model = new DeckModel
            {
                DeckName = "Joel Deck",
                DeckCategories = new List<DeckCategoryModel>() 
                {  
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=0 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=1 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=2 },
                    new DeckCategoryModel(){ CategoryName = string.Empty, Index=3 }

                    //Default categories for testing purposes
                    //new DeckCategoryModel(){ CategoryName = "Intelligence", Index=0 },
                    //new DeckCategoryModel(){ CategoryName = "Cuteness", Index=1 },
                    //new DeckCategoryModel(){ CategoryName = "Emotional", Index=2 },
                    //new DeckCategoryModel(){ CategoryName = "Boyfriend Material", Index=3 },
                    //new DeckCategoryModel(){ CategoryName = "Dress Sense", Index=4 }
                }
            };
            return View(model);
        }

        public ActionResult CreateDeck(string deckName, ICollection<DeckCategoryModel> deckCategories)
        {
            DeckModel model = new DeckModel
            {
                DeckName = deckName,
                DeckCategories = deckCategories
            };

            return View(model);
        }

        public PartialViewResult AddDeckCategory(int index)
        {
            return PartialView("PartialViews/_DeckCategoryPartial", new DeckCategoryModel() { CategoryName = string.Empty, Index = index });
        }

        public ActionResult SaveDeck(string deckName, ICollection<DeckCategoryModel> deckCategories, ICollection<CardModel> cards, IEnumerable<HttpPostedFileBase> cardImages)
        {
            SetupStorageContainer(deckName);

            //Save the Deck
            Guid deckId = _deckBusinessLogic.CreateDeck(new Deck() { Name = deckName });

            ////Save the Deck Categories
            foreach (DeckCategoryModel deckCategory in deckCategories)
            {
                Guid dcId = _deckCategoryBusinessLogic.CreateDeckCategory(new DeckCategory() { Id = Guid.NewGuid(), DeckId = deckId, Name = deckCategory.CategoryName });

                //Keep track of the deck Category GUIDs so that Card Categories can be linked up
                foreach (CardModel card in cards)
                {
                    foreach (CardCategoryModel cardCategory in card.CardCategories)
                    {
                        if (cardCategory.Index == deckCategory.Index)
                        {
                            cardCategory.DeckCategoryId = dcId;
                        }
                    }
                }
            }


            //Save the Cards
            int imageInc = 0;
            foreach (CardModel card in cards)
            {
                //Get the card image from the list of files
                HttpPostedFileBase image = cardImages.ElementAt(imageInc);
                imageInc++;

                //Create a guid for the card
                Guid cardGuid = Guid.NewGuid();

                // Retrieve reference to a blob named with this guid
                CloudBlockBlob blockBlob = container.GetBlockBlobReference( cardGuid.ToString() );

                //Upload the blob
                blockBlob.UploadFromStream(image.InputStream);

                //Create Card to Save
                Card newCard = new Card
                {
                    Id = cardGuid,
                    Name = card.CardName,
                    DeckId = deckId
                };

                //Save the card object
                _cardBusinessLogic.CreateCard(newCard);

                List<CardCategory> cardCategories = new List<CardCategory>();

                //Save the Card Category Values
                foreach (CardCategoryModel cardCategory in card.CardCategories)
                {
                    cardCategories.Add(new CardCategory
                    { 
                        Id = Guid.NewGuid(), 
                        DeckCategoryId = cardCategory.DeckCategoryId, 
                        Score = cardCategory.Value, 
                        CardId = newCard.Id 
                    });
                }

                //Save the Card Category objects
                _cardCategoryBusinessLogic.CreateCardCategory(cardCategories);
            }

            return RedirectToAction("View", new { id = deckId.ToString() });
        }

        public void SetupStorageContainer(string deckname)
        {
            //Retrieve the connection string
            string connStr = ConfigurationUtilities.GetConfigurationSetting("AzureConnectionString");

            //Retrieve storage account from connection string.
            storageAccount = CloudStorageAccount.Parse(connStr);

            //Create the blob client.
            blobClient = storageAccount.CreateCloudBlobClient();

            //Retrieve a reference to a container. 
            container = blobClient.GetContainerReference(deckname.ToLower().Replace(" ", string.Empty));

            //Create the container if it doesn't already exist.
            container.CreateIfNotExists();

            //Make the card images publicly accessible
            container.SetPermissions(
            new BlobContainerPermissions
            {
                PublicAccess = BlobContainerPublicAccessType.Blob
            });
        }
    }
}

JTT.WebApplication/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JTT.Domain.Enums;
using JTT.Interfaces;
using JTT.WebApplication.Models;
using JTT.WebApplication.Utilities;

namespace JTT.WebApplication.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginBusinessLogic _loginBusinessLogic;

        public LoginController(ILoginBusinessLogic loginBusinessLogic)
        {
            _loginBusinessLogic = loginBusinessLogic;
        }

        public ActionResult Index(string returnUrl)
        {
            return View(new LoginModel { RedirectURL = returnUrl });
        }

        public ActionResult Login(LoginModel loginModel)
        {
            var topTrumpsProvider = new TopTrumpsProvider(_loginBusinessLogic);
            var result = topTrumpsProvider.LoginUser(loginModel.Username, loginModel.Password);

            if (result == LoginResult.Success)
            {
                if(loginModel.RedirectURL != null)
                {
                    return Redirect(loginModel.RedirectURL);
                }

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index");
        }

        public ActionResult LoginAsAnonymous()
        {
            TopTrumpsProvider.LoginAsAnonymous();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            TopTrumpsProvider.LogoutUser();
            return RedirectToAction("Index");
        }
    }
}

JTT.WebApplication/Views/Shared/_Card.cshtml
@model JTT.WebApplication.Models.Game.TopTrumpsCard
    
<header>
    <img src="@Model.ImageAddress"/>
    <div class="titleContainer">
        <span class="title">@Model.Name</span>
    </div>
    <div class="slantedBlock"></div>
</header>

<div class="categories">
    <table class="selectable">
        @foreach (var item in Model.TopTrumpsCategories.OrderBy(c => c.Name))
        {
            <tr class="card-category" data-card-id="@Model.CardId" data-category-id="@item.CategoryId">
                <th>@item.Name</th>
                <th>@item.Value</th>
            </tr>
        }
    </table>
</div>

<footer>
    @*Your card*@
    &copy; Joel Top Trumps - @DateTime.Now.Year
</footer>

JTT.WebApplication/Views/Shared/_Layout.cshtml
@using JTT.WebApplication.Utilities
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>@ViewBag.Title - Joel Top Trumps</title>

        @Styles.Render(BundleConfig.CssStylesBundle)
        @Scripts.Render(BundleConfig.JqueryScriptBundle)
        @Scripts.Render(BundleConfig.ModernizrScriptBundle)
        @Scripts.Render(BundleConfig.JqueryValidateScriptBundle)
        
        <link rel="icon" href="@Url.Content("~/Content/Images/favicon.ico")">
    </head>
<body>
    <div class="header-container">
        <a href="@Url.Action("Index", "Home")">
            <img src="@Url.Content("~/Content/Images/joel.gif")" />
        </a>
        <ul class="navigation">
            <li>@Html.ActionLink("Matchmake", "Index", "Deck")</li>
            <li>@Html.ActionLink("Leaderboard", "Index", "Leaderboard")</li>
            <li>@Html.ActionLink("Decks", "All", "Deck")</li>
        </ul>

        <div class="user-status">
            @if (TopTrumpsProvider.GetLoggedinUser() != null)
            {
                <span>Hello @TopTrumpsProvider.GetLoggedinUser().Username!</span>
                @Html.ActionLink("Sign out", "Logout", "Login", null, new { @class = "yellow-link" })
            }
            else
            {
                <span>@Html.ActionLink("Log in", "Index", "Login", null, new { @class = "yellow-link" })</span>
            }
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render(BundleConfig.SignalRScriptBundle)

    @RenderSection("scripts", required: false)
    <script src="~/signalr/hubs"></script>
</body>

</html>

JTT.WebApplication/Views/Shared/_SearchableLeaderboard.cshtml
@using JTT.WebApplication.Utilities
@model JTT.WebApplication.Models.LeaderboardModel
    
@if (Model.LeaderboardPlayers.Any())
{
    <table class="leaderboard">
        <tr>
            <th>Position</th>
            <th>Username</th>
            <th>Wins</th>
            <th>Losses</th>
            <th>Average Playtime</th>
            <th>Total Playtime</th>
            @if (TopTrumpsProvider.IsUserCurrentlyLoggedIn() && !TopTrumpsProvider.IsUserAnonymous())
            {
                <th>Action</th>
            }
        </tr>
        @foreach (var leaderboardPlayer in @Model.LeaderboardPlayers.Select((item, index) => new { Item = item, Index = index }))
        {
            <tr>
                <td>@leaderboardPlayer.Item.Position</td>
                <td>@leaderboardPlayer.Item.Username</td>
                <td>@leaderboardPlayer.Item.Wins</td>
                <td>@leaderboardPlayer.Item.Losses</td>
                <td>@leaderboardPlayer.Item.AverageGameDuration.ToString("h'h 'm'm 's's'")</td>
                <td>@leaderboardPlayer.Item.TotalGameTime.ToString("h'h 'm'm 's's'")</td>
                @if (TopTrumpsProvider.IsUserCurrentlyLoggedIn() && TopTrumpsProvider.GetLoggedInUserId() != leaderboardPlayer.Item.UserId && !TopTrumpsProvider.IsUserAnonymous())
                {
                    <td>
                        <a href="#" class="challenge">Challenge?</a>
                        <div class="challenge-container">
                            @Html.DropDownList("Deck", new List<SelectListItem>(@Model.Decks.Select(d =>
                                    new SelectListItem { Text = d.Name, Value = d.Id.ToString() })),
                                    new { @id = "Decks", @class = "dropdown" })

                            <a href="#" class="submit" data-userid="@leaderboardPlayer.Item.UserId" onclick="return confirm('Challenge this player?');">Go!</a>
                        </div>
                    </td>
                }
                else if (TopTrumpsProvider.IsUserCurrentlyLoggedIn() && TopTrumpsProvider.GetLoggedInUserId() == leaderboardPlayer.Item.UserId)
                {
                    <td>
                        @Html.Raw("N/A")
                    </td>
                }
            </tr>
        }
    </table>
}
else
{
    Html.Raw("No players at the moment");
}

<script type="text/javascript">
    $(function () {
        bindEvents();
    });

    function bindEvents() {
        //On clicking challenge
        $(".challenge").click(function () {
            $(this).fadeOut(500, function () {
                $(this).parent().find('.challenge-container').fadeIn(500);
            });
        });

        //On clicking submit send off a message to a user about their challenge
        $(".submit").click(function () {
            var submit = $(this);
            var dropdown = submit.parent().find(".dropdown");
            var selectedDeckId = dropdown.find(":selected").val();
            var selectedUserId = submit.data("userid");

            //Perform a request to make a challenge
            $.ajax({
                url: "/Leaderboard/Challenge",
                type: "POST",
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify({ deckId: selectedDeckId, userId: selectedUserId }),
                success: function (bitlyLink) {
                    if (bitlyLink != "") {
                        location.href = bitlyLink;
                    }
                    else {
                        submit.parent().parent().html("Not sent");
                    }
                }
            });
        });
    }
</script>